# Conda environment specification. Details about the Conda environment file format:
# https://conda.io/docs/user-guide/tasks/manage-environments.html#create-env-file-manually

name: training_env
dependencies:
  - python=3.8.12
  - pip:
    - azureml-sdk==1.37.0
    - azureml-dataset-runtime[pandas,fuse]==1.37.0
    - scikit-learn==1.0.2
    - pandas==1.3.5
    - matplotlib==3.3.3
channels:
  - conda-forge
